# Generated by Django 3.2.6 on 2021-09-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_user_note_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='user',
        ),
    ]
